server:
  port: 8762

spring:
  application:
    name:
      eureka-server




eureka:
  instance:
    hostname: project-server
  client:
    register-with-eureka: true  # 是否向注册中心注册自己
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/
